### PR TITLE
Lps 94003 upgrade spring try2

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test:backend-hypersonic

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:stop

**Comment by ngriffin7a** [comment]
ci:test:norebase

**Comment by ngriffin7a** [comment]
ci:test:norebase

**Comment by ngriffin7a** [comment]
ci:test:norebase

**Comment by ngriffin7a** [comment]
@vicnate5 The "failures unique to this pull" in the first run of 190 out of 207 jobs passed 

is different than the "failures unique to this pull" in the final run of 185 out of 207 jobs passed 

Could you please take a look and see if there are any problems that this pull might actually be causing? Thanks.

**Comment by vicnate5** [comment]
@ngriffin7a Test results are looking much better. The only thing I see on here is some semver issues (which I expect are not related).

**Comment by ngriffin7a** [comment]
Thanks @vicnate5 !

**Pull request closed without merging**
