### PR TITLE
LPS-119991 Portal with JBoss and Wildfly failed to startup due to ParseError at liferay-ui.tld

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by vicnate5** [comment]
@ngriffin7a No regressions found during analysis. This should be good to forward.

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
