### PR TITLE
Lps 94003 upgrade to spring 5.2.x

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@vicnate5

Again, for the sake of convenience, here are the failures that you reported on the previous pull request attempt I made:

1. project template tests: https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/341897/

2. Unit test: https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/309964/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.portal.library/LibraryReferenceTest/testLibDependencyJarsInVersionsExt/

3. SF: https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/335344/AXIS_VARIABLE=0,label_exp=!master/consoleText

I fixed ##1, ##2, and most of the SF errors in ##3 (the ones that were my fault).

Please review at your earliest opportunity. I really appreciate your help!

Thanks,

-- Neil

**Comment by vicnate5** [comment]
@ngriffin7a Unit and SF tests are passing, but see https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/321521/

**Comment by ngriffin7a** [comment]
Thanks @vicnate5 -- inching ever closer to success! I hope to send another update later today.

**Pull request closed without merging**
