### PR TITLE
LPS-114465 Migrate from package com.liferay.spring.mock.web.portlet to com.liferay.portletmvc4spring.test.mock.web.portlet

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Analyzing tests from https://github.com/ngriffin7a/liferay-portal/pull/118#issuecomment-635607464 since testray is backed up for recent results today.

- Unique functional failures look unrelated
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1194437059&testrayRunIdA=1194658971&statusB=2
 
- Common test failures look unrelated
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1194437059&testrayRunIdA=1194658971&statusB=3

Investigating backend test batches

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

The most recent backend test batch failures in https://github.com/ngriffin7a/liferay-portal/pull/118#issuecomment-637025967 don't look related.

**Comment by ngriffin7a** [comment]
ci:forward

**Comment by ngriffin7a** [comment]
ci:forward

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 
pushed to https://github.com/brianchandotcom/liferay-portal/pull/89517

**Pull request closed without merging**
