### PR TITLE
LPS-93978 Develop the bean-portlet-spring-extension

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:forward

**Comment by ngriffin7a** [comment]
ci:forward

**Comment by vicnate5** [comment]
@ngriffin7a Go ahead and manually forward to BChan. The test failures here are unrelated.

A fix is in review for the race condition on IX_B27A301F (https://issues.liferay.com/browse/LPS-110102). I created a ticket for the shutdown error (https://issues.liferay.com/browse/LPS-112949), but this must be very rare since this has not been reported before.

**Comment by ngriffin7a** [comment]
ci:reopen

**Pull request closed without merging**
