### PR TITLE
LPS-132180

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by ngriffin7a** [comment]
@hhuijser Good start!
- For ActionURLBuilder & ResourceURLBuilder: With Portlet 3.0, javax.portlet.actionURL also as a `getRenderParameters()` method that returns an instance of `MutableRenderParameters` so we need `setRenderParameter` methods as well.
- For ResourceURLBuilder: I think we need `setResourceID(String id)` as well.

**Comment by ngriffin7a** [comment]
There might be more but that's all I can think of right now.

**Pull request closed without merging**
