### PR TITLE
Lps 94003 upgrade spring try2

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test:backend-hypersonic

**Comment by ngriffin7a** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:norebase

**Comment by ngriffin7a** [comment]
ci:stop

**Comment by ngriffin7a** [comment]
@vicnate5 Last minute merge conflict -- must have happened this morning after I ran the `ci:test:backend-hypersonic` batch. Closing.

**Comment by ngriffin7a** [comment]
See https://github.com/ngriffin7a/liferay-portal/pull/61

**Pull request closed without merging**
