### PR TITLE
Lps 94003 upgrade spring

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test:backend-hypersonic

**Comment by ngriffin7a** [comment]
ci:test:backend-hypersonic

**Comment by ngriffin7a** [comment]
@vicnate5 could you point me to the log that has full details of the aborted job? The link provided simply points to a log that states "Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted"

**Comment by vicnate5** [comment]
@ngriffin7a The log is not very helpful in this case, but this is an example of how to access
getResults

**Comment by ngriffin7a** [comment]
@vicnate5 Thanks for pointing that out. I agree that the log is not very helpful in this case. I'm roadblocked on this one until I can get more details -- is there a way I can run it locally and watch it timeout? Or is there a better approach to get this one resolved? Thanks.

**Comment by vicnate5** [comment]
@ngriffin7a The test is timing starting portal

You should be able to run this test with locally `ant -f build-test-batch.xml integration-hypersonic20-jdk8`
but I cannot promise it will work. I am trying it myself. The script will compile portal too.

See https://github.com/liferay/liferay-portal/blob/a9289a10aa4b9eab359e063be252fcfca8a545b7/build-test-batch.xml#L1418 for what it is doing.

```
test-class-group:
   [delete] Deleting directory /opt/dev/projects/github/liferay-portal/bundles/data
    [junit] -- listing properties --
    [junit] assert.logs=true
    [junit] ci.test.timeout.time=1200000
    [junit] company.web.id=liferay.com
    [junit] dl.file.entry.processors.trigger.synchronously=true
    [junit] include-and-override=test-portal-impl-ext.properties
    [junit] journal.transformer.regex.pattern.0=beta.sample.com
    [junit] journal.transformer.regex.replacement.0=production.sample.com
    [junit] junit.delay.factor=1
    [junit] portal.url=http://localhost:8080
    [junit] user.password=test
    [junit] 
    [junit] -- updated properties --
    [junit] assert.logs=true
    [junit] ci.test.timeout.time=1200000
    [junit] company.web.id=liferay.com
    [junit] dl.file.entry.processors.trigger.synchronously=true
    [junit] include-and-override=test-portal-impl-ext.properties
    [junit] journal.transformer.regex.pattern.0=beta.sample.com
    [junit] journal.transformer.regex.replacement.0=production.sample.com
    [junit] junit.delay.factor=1
    [junit] portal.url=http://localhost:8080
    [junit] user.password=test
    [junit] 
    [junit] Loading jar:file:/opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar!/system.properties
    [junit] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/test-classes/integration/system-ext.properties
    [junit] SLF4J: Class path contains multiple SLF4J bindings.
    [junit] SLF4J: Found binding in [file:/opt/dev/projects/github/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
    [junit] SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    [junit] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    [junit] SLF4J: Actual binding is of type [com.liferay.util.sl4fj.LiferayLoggerFactory]
    [junit] Loading jar:file:/opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar!/portal.properties
    [junit] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/test-classes/integration/portal-test.properties
    [junit] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/test-classes/integration/portal-test-ext.properties
    [junit] Running com.liferay.counter.service.CounterLocalServiceTest
    [junit] Testsuite: com.liferay.counter.service.CounterLocalServiceTest
    [junit] 22:40:14,287 WARN  [DialectDetector:101] Liferay is configured to use Hypersonic as its database. Do NOT use Hypersonic in production. Hypersonic is an embedded database useful for development and demonstration purposes. The database settings can be changed in portal-ext.properties.
    [junit] 22:40:14,319 INFO  [DialectDetector:159] Using dialect com.liferay.portal.dao.orm.hibernate.HSQLDialect for HSQL Database Engine 2.3
    [junit] May 06, 2019 10:40:39 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
    [junit] WARNING: org.xerial's sqlite-jdbc is not loaded.
    [junit] Please provide the jar on your classpath to parse sqlite files.
    [junit] See tika-parsers/pom.xml for the correct version.
    [junit] May 06, 2019 10:40:40 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
    [junit] WARNING: Tesseract OCR is installed and will be automatically applied to image files unless
    [junit] you've excluded the TesseractOCRParser from the default parser.
    [junit] Tesseract may dramatically slow down content extraction (TIKA-2359).
    [junit] As of Tika 1.15 (and prior versions), Tesseract is automatically called.
    [junit] In future versions of Tika, users may need to turn the TesseractOCRParser on via TikaConfig.
    [junit] May 06, 2019 10:40:40 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
    [junit] WARNING: TIFFImageWriter not loaded. tiff files will not be processed
    [junit] See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
    [junit] for optional dependencies.
    [junit] J2KImageReader not loaded. JPEG2000 files will not be processed.
    [junit] See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
    [junit] for optional dependencies.
    [junit] 
    [junit] 22:40:50,510 WARN  [EmbeddedElasticsearchConnection:288] Liferay is configured to use embedded Elasticsearch as its search engine. Do NOT use embedded Elasticsearch in production. Embedded Elasticsearch is useful for development and demonstration purposes. Refer to the documentation for details on the limitations of embedded Elasticsearch. Remote Elasticsearch connections can be configured in the Control Panel.
    [junit] 
    [junit]     __    ____________________  _____  __
    [junit]    / /   /  _/ ____/ ____/ __ \/   \ \/ /
    [junit]   / /    / // /_  / __/ / /_/ / /| |\  /
    [junit]  / /____/ // __/ / /___/ _, _/ ___ |/ /
    [junit] /_____/___/_/   /_____/_/ |_/_/  |_/_/
    [junit] 
    [junit] Starting Liferay Community Edition Portal 7.2.0 CE RC2 (Mueller / Build 7200 / May 2, 2019)
    [junit] 
    [junit] Loading jar:file:/opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar!/portal.properties
    [junit] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/test-classes/integration/portal-test.properties
    [junit] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/test-classes/integration/portal-test-ext.properties
    [junit] Executing verifiers registered for com.liferay.portal.security.sso.cas
    [junit] Executing verifiers registered for com.liferay.portal.security.sso.opensso
    [junit] Executing verifiers registered for com.liferay.portal.security.sso.ntlm
    [junit] Executing verifiers registered for com.liferay.portal.security.sso.google
    [junit] Executing verifiers registered for com.liferay.portal.security.sso.openid
    [junit] Executing verifiers registered for com.liferay.portal.security.sso.facebook.connect
    [junit] Executing verifiers registered for com.liferay.portal.security.sso.token.shibboleth
    [junit] Executing verifiers registered for com.liferay.portal.security.sso.token.siteminder
    [junit] Executing verifiers registered for com.liferay.systemevent.internal.verify
    [junit] Executing verifiers registered for com.liferay.portal.security.ldap
    [junit] Executing verifiers registered for com.liferay.message.boards.service
    [junit] May 06, 2019 10:42:07 PM org.apache.shindig.gadgets.features.FeatureResourceLoader$UriResource getContent
    [junit] WARNING: Unable to retrieve remote library from http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js
    [junit] May 06, 2019 10:42:07 PM org.apache.shindig.gadgets.features.FeatureResourceLoader$UriResource getContent
    [junit] WARNING: Unable to retrieve remote library from http://www.google-analytics.com/urchin.js
    [junit] May 06, 2019 10:42:07 PM org.apache.shindig.gadgets.features.FeatureResourceLoader$UriResource getContent
    [junit] WARNING: Unable to retrieve remote library from http://www.google.com/ig/lib/libanalytics.js
    [junit] May 06, 2019 10:42:07 PM org.apache.shindig.gadgets.features.FeatureResourceLoader$UriResource getContent
    [junit] WARNING: Unable to retrieve remote library from http://www.google.com/ig/lib/libga.js
    [junit] 22:42:20,776 INFO  [main][SystemCheckOSGiCommands:54] System check is enabled. You can run a system check with the command "system:check" in Gogo shell.
```

**Comment by ngriffin7a** [comment]
@vicnate5 Thanks, I'm running it locally too. I'll let you know how it works out.

**Comment by vicnate5** [comment]
It won't work. Has a dependency on Jenkins stuff, which is what I was afraid of.

**Comment by vicnate5** [comment]
@ngriffin7a found my old notes, this works for me.

Step 3 will start the portal

1. `ant -f build-test.xml record-test-class-file-names -Dtest.batch.name=integration-hypersonic20-jdk8`
2. `ant -f build-test.xml set-portal-impl-portal-test-ext-properties`
3. `cd portal-impl && ant test-class-group -Dtest.class.group.index=0`

 I really don't like that we cannot just run the batch locally...I don't know how other devs deal with this.

**Comment by ngriffin7a** [comment]
@vicnate5 I can't get past step 1. This is what I see, which seems to be CI/Jenkins dependent:
```
BUILD FAILED
/Users/ngriffin/Projects/liferay.com/liferay-portal/build-test.xml:10295: The following error occurred while executing this line:
/Users/ngriffin/Projects/liferay.com/liferay-portal/build-test.xml:2789: Sourced file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.Job; 		import com.lifera . . . '' : Typed variable declaration : Method Invocation JobFactory.newJob : at Line: 9 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.Job; 					import com.lifera . . . '' : JobFactory .newJob ( project .getProperty ( "top.level.job.name" ) , project .getProperty ( "env.CI_TEST_SUITE" ) , project .getProperty ( "portal.branch.name" ) , project .getProperty ( "env.REPOSITORY_NAME" ) )

Target exception: java.lang.ExceptionInInitializerError
```

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by ngriffin7a** [comment]
See https://github.com/ngriffin7a/liferay-portal/pull/56

**Pull request closed without merging**
