### PR TITLE
Lps 94003 upgrade to spring 5.2.x

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@vicnate5: Here is the failure from the previous PR:

>> Unit and SF tests are passing, but see https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/321521/

I did what Greg Amerson and Lawrence Lee said to do in order to fix it. Please review the test results and let me know if we're good-to-go.

Thanks,

Neil

**Comment by vicnate5** [comment]
@ngriffin7a Looking good! This looks ready to push forward.

FYI I will be out until 2020. Mention @koor4356 if you need help reviewing an test results next week.

**Comment by ngriffin7a** [comment]
Thanks @vicnate5 ! Merry Christmas and Happy New Year!

**Pull request closed without merging**
