### PR TITLE
Lps 94003 upgrade spring

### PR DESCRIPTION
**Pull request by ngriffin7a**
ci:test

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@ngriffin7a Waiting on integration test batches, but the functional tests look good on this pull.

**Comment by vicnate5** [comment]
@ngriffin7a 
Unique Integration test failure: https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/264434/AXIS_VARIABLE=18,label_exp=!master/testReport/junit/com.liferay.message.boards.search.test/MBMessageIndexerSummaryTest/testSummarySearchFullSubject/

Another one, but unsure if it is related: https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/264434/AXIS_VARIABLE=27,label_exp=!master/testReport/junit/com.liferay.portal.vulcan.internal.jaxrs.context.provider.test/AcceptLanguageContextProviderTest/testCreateContextWithAuthenticatedUser/

**Comment by ngriffin7a** [comment]
See https://github.com/ngriffin7a/liferay-portal/pull/48

**Pull request closed without merging**
