### PR TITLE
Lps 94003 upgrade to spring 5.2.x

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@ngriffin7a Most of the tests look good. There are however some unique integration test failures related to this change:

1. 
```
com.liferay.portal.util.mail.test.MailEngineTest > classMethod FAILED
    org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.util.test [1069]
      Unresolved requirement: Import-Package: org.springframework.mock.web.portlet
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
        at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
        at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
```
Full log: https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/303018/AXIS_VARIABLE=33,label_exp=!master/consoleText

2. 
```
com.liferay.journal.search.test.JournalArticleMultiLanguageSearchJapaneseSummaryTest > testJapaneseSummaryHighlightedTermWithWordBoundaries FAILED
    java.lang.NullPointerException
    	at org.springframework.http.HttpHeaders.lambda$setAcceptLanguageAsLocales$1(HttpHeaders.java:506)
    	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    	at org.springframework.http.HttpHeaders.setAcceptLanguageAsLocales(HttpHeaders.java:507)
    	at org.springframework.mock.web.MockHttpServletRequest.updateAcceptLanguageHeader(MockHttpServletRequest.java:804)
    	at org.springframework.mock.web.MockHttpServletRequest.setPreferredLocales(MockHttpServletRequest.java:799)
    	at com.liferay.portal.search.test.util.SummaryFixture.createHttpServletRequest(SummaryFixture.java:100)
    	at com.liferay.portal.search.test.util.SummaryFixture.createPortletRequest(SummaryFixture.java:115)
    	at com.liferay.portal.search.test.util.SummaryFixture.getSummary(SummaryFixture.java:88)
    	at com.liferay.portal.search.test.util.SummaryFixture.assertSummary(SummaryFixture.java:78)
    	at com.liferay.portal.search.test.util.SummaryFixture.assertSummary(SummaryFixture.java:68)
```
Full log: https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/303018/AXIS_VARIABLE=17,label_exp=!master/consoleText

3. 
```
com.liferay.document.library.web.internal.exportimport.portlet.preferences.processor.test.DLExportImportPortletPreferencesProcessorTest > classMethod FAILED
    org.osgi.framework.BundleException: Could not resolve module: com.liferay.document.library.web.test [1069]
      Unresolved requirement: Import-Package: org.springframework.mock.web.portlet
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
        at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
        at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
```
Full log: https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/303018/AXIS_VARIABLE=11,label_exp=!master/consoleText

**Comment by ngriffin7a** [comment]
Thanks @vicnate5 I will fix it!

**Pull request closed without merging**
