### PR TITLE
LPS-84367 Fix tck v3.0 tests

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@julien I confirmed that this commit fixes the TCK test failures in Chrome and Firefox, but there are still problems with Safari.

For example, with Safari if I click on the V3PortletHubTests_SPEC_23_JSPRP_Action1 and V3PortletHubTests_SPEC_23_JSPRP_Action2 buttons, nothing happens.

In addition, with Safari none of the buttons in the following portlets work:
- PortletHubTests_SPEC_23_JSURL
- PortletHubTests_SPEC_23_JSAction
- PortletHubTests_SPEC_23_JSPA

**Comment by ngriffin7a** [comment]
@julien There are also problems with the PortletHubDemo -- the portlets there should work the same in Liferay as they do in Pluto.

With Safari, I saw the following problems:
1. In the "PH Image Selection Portlet" (image viewer) clicking on the radio buttons for golfball/baseball/fussball does not update the image displayed in the "PH Resource Portlet" (image viewer)
2. Typing in a text message in the "PH Color Selection Portlet" and clicking the "Send" button does not cause the message to display in the "Message Box Portlet"

With Chrome and Firefox, I saw the following problems:
1. Same as #1 above

**Comment by julien** [comment]
Hi @ngriffin7a 

Thanks for the feedback. 

Concerning Safari, I'm testing with version 11.1.2 (11605.3.8.1) if that can help, and also testing the same way as in other browsers (default "test" user logged in).

Concerning tests: **V3PortletHubTests_SPEC_23_JSPRP_Action1** and  **V3PortletHubTests_SPEC_23_JSPRP_Action2**

When I click on the buttons to run these tests, this is what is actually logged into Tomcat's console

```
2018-08-14 07:03:46.369 WARN  [http-nio-8080-exec-1][SecurityPortletContainerWrapper:393] User 0 is not allowed to access URL http://localhost:3000/web/guest/v3portlethubtests and portlet PortletHubTests_SPEC_23_JSPRP_TX_WAR_tckV3PortletHubTests
```

Although I'm logged in a *"test test"*. 

Here's a .gif of this in action:

v3portlethubtests_spec_23_jsprp_action1

Concerning **PortletHubTests_SPEC_23_JSURL** tests, I managed to launch all tests and see the "Test succeeded" message.

portlethubtests_spec_23_jsurl

Concerning the **PortletHubTests_SPEC_23_JSAction** tests, I get the same error concerning User 0 not being allowed to access the URL as shown in this gif

portlethubtests_spec_23_jsaction

* Although the last test is marked as "succeeded" *

Concerning the **PortletHubTests_SPEC_23_JSPA** tests, I was able to run them succesfully

portlethubtests_spec_23_jspa

Concerning the **PortletHubDemo**, since I switched back to master I can't get this portlet working (nor the v3.0ParameterTests portlet), I will try re-importing the lar file and re-deploying the tck .war files to see if that helps, if not I'll probably send you more information.

Thanks

**Pull request closed without merging**
