### PR TITLE
actionScopedRequestAttributes

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @ngriffin7a 

This is Leon's attempt to implement container runtime option actionScopedRequestAttributes, which is a "must" for the container to support, with my SF merged into the commits (I didn't touch the actual logic).

This pull can be mainly divided into two parts: 1) removing attributes set during a phase at the end of the phase, and 2) implementing actionScopedRequestAttributes.

Could you take a look at the implementation and point out the issues, especially for the compatibility with the Spec?

Thanks!

By the way, 1) is for Spec 3.0 chapter 14.1.2,

> Requests attributes are removed at the end of a request processing phase.

And this statement doesn't exist in 2.0 Spec.

**Comment by dantewang** [comment]
@ngriffin7a additionally, the changes in this pull can pass normal CI (no unique failure) and TCK3 V2 tests.

cc @ChiZelin @vsingleton

**Comment by vsingleton** [comment]
@dantewang Has this PR been tested with the latest portlet tck3 master?  The reason I ask is that https://issues.apache.org/jira/browse/PLUTO-686 has now committed fixes which expect a certain number of runtime options, and it looks like this pr may add a runtime option.  So this might cause a regression in PLUTO-686.  

If it does cause a regression, it should not be too hard to fix, but I am just curious if you tested with the latest master tck?

cc @ChiZelin @ngriffin7a

**Comment by ngriffin7a** [comment]
Closing this issue. Sorry for the confusion. For more information see https://issues.apache.org/jira/browse/PLUTO-687

**Pull request closed without merging**
