### PR TITLE
Lps 94003 upgrade to spring 5.2.x

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@vicnate5: I fixed the spring-related errors you pointed out in the previous pull request and tried a new `ci:test` in this latest pull request. If you could please look over the test results I'd like to get your approval to send it on to Shuyang for his review. Thanks!

**Comment by vicnate5** [comment]
@ngriffin7a A few more issues. I apologize for missing these on the previous PR, I was very thorough on this one.

1. Project template: https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/343809/

2. Unit test: https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356418/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.portal.library/LibraryReferenceTest/testLibDependencyJarsInVersionsExt/

3. Error caught during an integration test run, could be related, I am not sure what test it is tied to
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/341810/AXIS_VARIABLE=16,label_exp=!master/testReport/junit/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanOSGiLog/

4. SF issue:
`java.lang.RuntimeException: Unable to format ./nbproject/project.properties`
https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356416/AXIS_VARIABLE=0,label_exp=!master/consoleText

Also heads up that a couple MVC functional tests (`SampleProjectTemplates#WarMvcPortletTemplateSmoke` and `SampleProjectTemplates#MvcPortletTemplateSmoke`) are broken on CI and did not run here.
https://issues.liferay.com/browse/LRCI-858

**Comment by ngriffin7a** [comment]
Thanks @vicnate5 I'll take care of it!

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:stop

**Pull request closed without merging**
