### PR TITLE
Lps 94003 upgrade spring

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test:backend-hypersonic

**Comment by ngriffin7a** [comment]
@vicnate5 Could you please take a look at the aborted job in the "failures unique to this pull"? I can't see anything significant in the log. Thanks.

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
@ngriffin7a Failures for the aborted job can be seen here https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/162685/

Looks ok, re-running just to safe.

**Comment by ngriffin7a** [comment]
@vicnate5 Thanks for taking a look. The two "es-ES" failures might very well be caused by the Spring upgrade. I'm looking into that now. I've already fixed the final nbproject/project.properties failure locally. Hope to send a new PR in the next few hours and get an all clear today at some point.

**Comment by ngriffin7a** [comment]
@vicnate5 The modules-integration-hypersonic20-jdk8 job aborted again. What's the link for the detailed failures? Are they the same as last time?

**Comment by vicnate5** [comment]
@ngriffin7a https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/265094/

**Comment by vicnate5** [comment]
```
org.junit.ComparisonFailure: expected:<...epted languages: es-[ES]> but was:<...epted languages: es-[es]>
```

**Comment by ngriffin7a** [comment]
See https://github.com/ngriffin7a/liferay-portal/pull/53

**Pull request closed without merging**
