### PR TITLE
Lps 94003 upgrade spring

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by jpince** [comment]
I see this in batches that aborted, and there are a lot
```
[junit] May 01, 2019 3:47:02 PM org.apache.shindig.gadgets.features.FeatureResourceLoader$UriResource getContent
    [junit] WARNING: Unable to retrieve remote library from http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js
    [junit] May 01, 2019 3:47:02 PM org.apache.shindig.gadgets.features.FeatureResourceLoader$UriResource getContent
    [junit] WARNING: Unable to retrieve remote library from http://www.google-analytics.com/urchin.js
    [junit] May 01, 2019 3:47:02 PM org.apache.shindig.gadgets.features.FeatureResourceLoader$UriResource getContent
    [junit] WARNING: Unable to retrieve remote library from http://www.google.com/ig/lib/libanalytics.js
    [junit] May 01, 2019 3:47:02 PM org.apache.shindig.gadgets.features.FeatureResourceLoader$UriResource getContent
    [junit] WARNING: Unable to retrieve remote library from http://www.google.com/ig/lib/libga.js
```
not sure if that's related to your changes

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by vicnate5** [comment]
@ngriffin7a Will have to finish my analysis tomorrow, but the non-Tomcat app servers all start with errors.

Wildfly: https://gist.github.com/vicnate5/ead7ba8cb9393d01428be17f46d44443

Full Log: https://testray.liferay.com/reports/production/logs/test-1-8/1556744897882/test-portal-acceptance-pullrequest(master)/3424/functional-smoke-wildfly110-mariadb102-jdk8/0/0/jenkins-console.txt.gz

JBoss: https://gist.github.com/vicnate5/dd32e226d97bc128a57a6175731f1428
Websphere: https://gist.github.com/vicnate5/e0cf1a068147cc6044a736816f431c7b
Weblogic: https://gist.github.com/vicnate5/b02be3e905800e826b08148a1581824f

**Comment by ngriffin7a** [comment]
@vicnate5 Thank you for helping to isolate the problems with the non-Tomcat servers. You can hold-off on further analysis for now because the "classmate" dependency (com.fasterxml.*) is likely the root problem that I need to solve. Thanks again! :)

**Comment by ngriffin7a** [comment]
See https://github.com/ngriffin7a/liferay-portal/pull/47

**Pull request closed without merging**
