### PR TITLE
Lps 94003 upgrade spring

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test:backend-hypersonic

**Comment by ngriffin7a** [comment]
ci:retest:backend-hypersonic

**Comment by ngriffin7a** [comment]
See https://github.com/ngriffin7a/liferay-portal/pull/49

**Comment by vicnate5** [comment]
@ngriffin7a 

Still seeing (and now on Journal tests)
```
java.lang.NoClassDefFoundError: com/liferay/spring/mock/web/portlet/MockRenderRequest
```

Also see the `unit-jdk8` test failures in the report above

**Comment by ngriffin7a** [comment]
Thanks @vicnate5 I think I got 'em fixed in #49 -- let's wait for those test results.

**Pull request closed without merging**
