### PR TITLE
Lps 115019 factories impls adapter 74 rebase

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:frontend

**Comment by vicnate5** [comment]
@zhangyan0701 can you scan this PR?

**Comment by vicnate5** [comment]
ci:test:frontend

**Comment by ngriffin7a** [comment]
@vicnate5 I'm not able to access any of the failures from the recent `ci:test:frontend`

I'd appreciate it if you could recommend next steps. Thanks.

**Comment by vicnate5** [comment]
@ngriffin7a There was a unique failure on the first run, but it did not occur when I re-ran. This is good to go. Will trigger forward.

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
